import turtle

t = turtle.Turtle()
s = turtle.Turtle()
w = turtle.Turtle()

t.speed(0)
window = turtle.Screen()
window.bgcolor("#69C5FF")


def grass():
    t.penup()
    t.goto(-700, -250)
    t.pendown()
    t.begin_fill()
    t.color("#3cb371")
    for i in range(4):
        t.forward(2000)
        t.right(90)
    t.end_fill()


def feather(color):
    t.fillcolor(color)
    t.begin_fill()
    t.circle(50, 70)
    t.left(110)
    t.circle(50, 70)
    t.end_fill()


def legs(x, y):
    t.penup()
    t.pensize(2)
    t.color("black")
    t.goto(x - 30, y - 30)
    t.left(90)
    t.pendown()
    t.forward(20)
    t.right(30)
    t.forward(10)
    t.backward(10)
    t.left(30)
    t.forward(10)
    t.backward(10)
    t.left(30)
    t.forward(10)
    t.backward(10)
    t.right(30)
    t.backward(30)
    t.penup()
    t.goto(x - 30, y - 40)
    t.pendown()
    t.right(20)
    t.forward(15)
    t.right(30)
    t.forward(10)
    t.backward(10)
    t.left(30)
    t.forward(10)
    t.backward(10)
    t.left(30)
    t.forward(10)
    t.backward(10)
    t.right(30)
    t.backward(20)


def body(x, y):
    t.penup()
    t.goto(x, y)
    t.pendown()
    t.begin_fill()
    t.color("#8b4513")
    t.circle(40)
    t.end_fill()
    t.penup()
    x += 30
    y += 30
    t.goto(x, y)
    t.pendown()
    t.color("black")
    t.up()
    feather("yellow")
    t.left(90)
    feather("orange")
    t.left(90)
    feather("red")
    t.left(90)
    feather("#ffd700")
    legs(x, y)


def head(x, y, color):
    t.penup()
    t.pensize(2)
    t.goto(x - 40, y + 90)
    t.pendown()
    t.begin_fill()
    t.color("brown")
    t.circle(20)
    t.end_fill()
    t.color("orange")
    t.forward(5)
    t.left(330)
    t.forward(5)
    t.left(30)
    t.penup()
    t.goto(x - 30, y + 100)
    t.pendown()
    t.color("white")
    t.dot(5)


def turkey(x, y):
    t.penup()
    t.goto(x, y)
    t.setheading(0)
    t.penup()
    body(x, y)
    head(x, y, "black")


def tree():
    s.pensize(10)
    s.left(90)
    s.color("brown")
    s.forward(200)
    s.right(90)
    s.forward(10)
    s.right(90)
    s.forward(200)
    s.left(90)
    s.forward(10)
    s.left(90)
    s.forward(200)
    s.begin_fill()
    s.color("dark green")
    s.right(90)
    s.forward(50)
    s.left(130)
    s.forward(90)
    s.left(100)
    s.forward(90)
    s.left(130)
    s.forward(90)
    s.end_fill()


grass()
s.penup()
s.goto(-300, -300)
s.pendown()
tree()
s.penup()
s.goto(-100, -300)
s.pendown()
tree()
s.penup()
s.goto(100, -300)
s.pendown()
tree()
#x  = int(input("give me a num between -350 and 350"))
# y = int(input("give me a num between -350 and 350"))

# turkey(x,y)

turkey(300, -250)
turkey(200, 50)
turkey(-200, -250)
turkey(-100, 50)
turkey(100,100)
w.penup()
w.goto(-300, 300)
w.pendown()
w.write("Happy Thanksgiving!", font = 60)
